week8/blog-app/config/urls.py
from django.contrib import admin
from django.urls import path, include

from posts.views import list

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', list, name='home'),  # 메인 페이지 지정

    path('accounts/', include('accounts.urls')),  # accounts 앱의 urls 사용
    path('posts/', include('posts.urls')),  # posts 앱의 urls 사용
]

week8/blog-app/posts/urls.py
from django.urls import path

from posts.views import list, detail, create, update, delete  # new

app_name = 'posts'

urlpatterns = [
    path('<int:id>/update/', update, name='update'),
    path('<int:id>/delete/', delete, name='delete'),
    path('', list, name='list'),
    path('<int:id>/', detail, name='detail'),
    # path('new/', new, name='new'),
    path('create/', create, name='create'),
]

week8/blog-app/posts/views.py
from datetime import datetime

from django.contrib.admin.decorators import register
from django.shortcuts import render, redirect

from .models import Post

def delete(request, id):  # url 패턴의 /delete/<int:id>/ 의 id 값으로 데이터베이스 조회
    """ 게시글 삭제 View """
    context = {}
    post = Post.objects.get(id=id)  # Post 모델으 id 필드가 id인 데이터 조회
    if request.method == 'POST':
        post.delete()  # POST 요청인 경우 데이터 삭제
        return redirect('posts:list')  # url name list url로 리다이렉트 응답
    else:
        context.update(post=post)  # 10 줄에서 생성한 context 변수에 post 키로 post 값 업데이트
        return render(request, 'posts/confirm_delete.html', context)

def update(request, id):  # url 패턴의 /update/<int:id>/ 의 id 값으로 데이터베이스 조회
    context = {'title':'글 수정', 'submit_text': '수정하기'}  # form.html 사용 시 제목과 제출 버튼 이름 지정
    post = Post.objects.get(id=id)  # Post 모델으 id 필드가 id인 데이터 조회
    if request.method == 'POST':
        title = request.POST['title']  # form > input name이 title 값 가져오기
        content = request.POST['content']  # form > input name이 content 값 가져오기
        created_by = request.POST['created_by']  # form > input name이 created_by 값 가져오기
        
        post.title = title  # 21 줄에서 조회한 객체의 title 값 변경
        post.content = content  # 21 줄에서 조회한 객체의 content 값 변경
        post.created_by = created_by  # 21 줄에서 조회한 객체의 created_by 값 변경
        post.save()  # 데이터베이스에 반영(저장)
        return redirect('posts:detail', id)  # url 패턴 detial에 id값을 넣어 리다이렉트
    else:
        context.update(post=post)  # form에 기존 값 추가를 위해 21에서 조회한 Post 인스턴스 context에 업데이트
        return render(request, 'posts/form.html', context)
        
        

def list(request):
    post_all = Post.objects.all()  # Post 모델의 전체 데이터 조회 
    context = {'post_all': post_all}  # 응답의 context 데이터 생성
    return render(request, 'posts/list.html', context)  # 요청에 응답 함수, 'list.html'은 파일명이며 templates 폴더에 존재해야 함

def detail(request, id):
    post = Post.objects.get(id=id)  # Post 모델의 특정 데이터 조회
    context = {'post': post}
    return render(request, 'posts/detail.html', context)

# def new(request):
#         context = {'title':'글 등록', 'submit_text': '등록하기'}
#         return render(request, 'form.html', context)
    
def create(request):
    if request.method == 'POST':
        now = datetime.now()  # 현재 시간을 구하기 위한 함수
        title = request.POST['title']  # 클라이언트에서 POST 요청으로 넘어온 form의 name=title인 값을 title 변수에 할당
        content = request.POST['content']  # 클라이언트에서 POST 요청으로 넘어온 form의 name=content인 값을 content 변수에 할당
        created_by = request.POST['created_by']  # 클라이언트에서 POST 요청으로 넘어온 form의 name=created_by인 값을 created_by 변수에 할당
        post = Post.objects.create(
            title=title,  # Post 모델 title 필드에 title 변수 값 입력
            content=content,  # Post 모델 content 필드에 content 변수 값 입력
            created_by=created_by,  # Post 모델 created_by 필드에 created_by 변수 값 입력
            created_at=now,  # Post 모델 created_at 필드에 now 변수 값 입력
        )
        return redirect('home')
    else:
        context = {'title':'글 등록', 'submit_text': '등록하기'}
        return render(request, 'posts/form.html', context)

week8/blog-app/templates/partials/footer.html
<footer style="width: 100%; height: 60px; background-color: gray;">
    푸터
</footer>

week8/blog-app/templates/partials/header.html
<header style="width: 100%; height: 60px; background-color: gray;">
    헤더
</header>

week8/blog-app/templates/posts/bootstrap.html
{% extends 'base.html' %}
{% block title %}글 목록{% endblock %}
{% block content %}
<div class="row">
    <div class="col-sm-12 col-md-6 col-lg-3">
        카드
    </div>
    <div class="col-sm-12 col-md-6 col-lg-3">
        카드
    </div>
    <div class="col-sm-12 col-md-6 col-lg-3">
        카드
    </div>
    <div class="col-sm-12 col-md-6 col-lg-3">
        카드
    </div>
</div>
<!-- <h1>글 목록 페이지</h1>
<div><a href="{% url 'create' %}" class="btn btn-primary">글쓰기</a></div>
<table class="table">
    <tr>
        <th>번호</th>
        <th>제목</th>
        <th>작성자</th>
        <th>작성일</th>
    </tr>
    {% for post in post_all %}
    <tr>
        <td>{{ post.id }}</td>
        <td><a href="{% url 'detail' post.id %}">{{ post.title }}</a></td>
        <td>{{ post.created_by }}</td>
        <td>{{ post.created_at }}</td>
    </tr>
    {% endfor %}
</table> -->
{% endblock %}

week8/blog-app/templates/posts/detail.html
{% extends 'base.html' %}

{% block title %}글 상세{% endblock %}

{% block content %}
<h1>글 상세페이지</h1>
{% include 'mixins/post_card.html' %}
<a href="{% url 'posts:list' %}">목록보기</a>
<a href="{% url 'posts:update' post.id %}">수정하기</a>
<a href="{% url 'posts:delete' post.id %}">삭제하기</a>
{% endblock %}